travis:
  secure:
    BINSTAR_TOKEN: ULVqe/ZNpt2GHJS9XGNIWXOLRFHHByLECu3tifSisCVi+xZ2W9m5rVMdocDUWRIA1ipGkGmxhEToptV75H25zeXBCCYxROGG+5ikhuPa0cAaKjJo8OdkCAZO8vhQzsRP0LluYkUvdvhzl7kqoPKykdRyr4F/SjkOC1JzhEIqhxtQAtVD6QiGbbQ1egUCKZUzrUVqDonYqmq27bI6/Sb6Y8PKzXVnLL8fZY7TUb1N1WZpS7y3XhqZ3PdL3egonZ/aA9hdwRSrmzGgOQoO1B8i8UKXjuCyGE1Ejn0n2z7fsfFAjv4MuuspeZcC7rxnLtm83jCKiZE6q/0IK4LmAM1Hc+3UW/P/ZMClRpPccHvggZqzwvsyOeMsM9W33cz/1nVin3fTjoFEUGiHScMdVWxJ4AMNfriyjiMXgWpsJEpFoesXCiyYbqnsUoCBmCENwQqTondy62wyvrqKBO1Lrhe7k3wCgavc6l0RbfiEbrMr8AGZFl/pq6rlxkp4VpuzYBBJQXipYLTk/ilwKghpOI/OQL4acAKzwW257w6bOmfeG3OV9x3LyadqZ3pwX8Yx22BITlEy2X992HDw01Q+ukrrROr/QnomgVAr9xmsvzCpRbsa1A8u50SUW5levMIKUaOh60SsjxYFJFxWZaM8+LOC1dsc57YB44mT4/c1JCbC/mQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
